language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

scripts:
  - npm run lint
  - 'npm run lint:style'
  - npm run test
  - npm run build

branches:
  only:
    - master

after_script:
  - test $TRAVIS_BRANCH == "master" && bash deploy.sh
