language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

before_install:
  - npm run lint
  - 'npm run lint:style'

install:
  - npm run build

scripts:
  - npm run test

after_success:
  - test $TRAVIS_BRANCH == "master" && bash deploy.sh


branches:
  only:
    - master
