language: node_js

node_js:
  - 4
  - 6

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@3

scripts:
  - npm run lint
  - 'npm run lint:style'
  - npm run test
  - npm run build

branches:
  only:
    - master

after_success:
  - test $TRAVIS_BRANCH == "master" && bash deploy.sh
