// AllForms container
export const FETCH_FORMS = 'FETCH_FORMS'
export const FETCH_FORMS_SUCCESS = 'FETCH_FORMS_SUCCESS'
export const FETCH_FORMS_ERROR = 'FETCH_FORMS_ERROR'
export const DELETE_FORM = 'DELETE_FORM'
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS'
export const DELETE_FORM_ERROR = 'DELETE_FORM_ERROR'

// NewForm container
// questions
export const ADD_QUESTION = 'ADD_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'
export const EDIT_TITLE_QUESTION = 'EDIT_TITLE_QUESTION'
export const CHANGE_REQUIRED = 'CHANGE_REQUIRED'
export const ADD_CHOICE = 'ADD_CHOICE'
export const DELETE_CHOICE = 'DELETE_CHOICE'
export const CHANGE_CHOICE = 'CHANGE_CHOICE'
export const CHANGE_TEXT = 'CHANGE_TEXT'
export const DRAG_QUESTION = 'DRAG_QUESTION'
export const SAVE_FORM = 'SAVE_FORM'
export const SAVE_FORM_SUCCESS = 'SAVE_FORM_SUCCESS'
export const SAVE_FORM_ERROR = 'SAVE_FORM_ERROR'
export const VALIDATION = 'VALIDATION'
export const VALIDATION_SUCCESS = 'VALIDATION_SUCCESS'
export const VALIDATION_ERROR = 'VALIDATION_ERROR'
// notifications
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION'
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS'

// extraData
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION'

// Browser container
export const FETCH_ITEM = 'FETCH_ITEM'
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS'
export const FETCH_ITEM_ERROR = 'FETCH_ITEM_ERROR'
